from . import hr
from . import hr_medical_insurance_type
from . import hr_contract
from . import hr_work_location
from . import hr_start_work
from . import hr_payslip
from . import hr_payslip_line
from . import hr_leave
from . import hr_payroll
